Traceback (most recent call last):
  File "/Users/kvarada/opt/miniconda3/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/kvarada/opt/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/kvarada/opt/miniconda3/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/kvarada/opt/miniconda3/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/kvarada/opt/miniconda3/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/kvarada/opt/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/kvarada/opt/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/kvarada/opt/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
train_df, test_df = train_test_split(spotify_df, test_size=0.2, random_state=321)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Input [0;32mIn [5][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m train_df, test_df [38;5;241m=[39m [43mtrain_test_split[49m[43m([49m[43mspotify_df[49m[43m,[49m[43m [49m[43mtest_size[49m[38;5;241;43m=[39;49m[38;5;241;43m0.2[39;49m[43m,[49m[43m [49m[43mrandom_state[49m[38;5;241;43m=[39;49m[38;5;241;43m321[39;49m[43m)[49m

File [0;32m~/opt/miniconda3/envs/cpsc330/lib/python3.10/site-packages/sklearn/model_selection/_split.py:2447[0m, in [0;36mtrain_test_split[0;34m(test_size, train_size, random_state, shuffle, stratify, *arrays)[0m
[1;32m   2443[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mAt least one array required as input[39m[38;5;124m"[39m)
[1;32m   2445[0m arrays [38;5;241m=[39m indexable([38;5;241m*[39marrays)
[0;32m-> 2447[0m n_samples [38;5;241m=[39m [43m_num_samples[49m[43m([49m[43marrays[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m[43m)[49m
[1;32m   2448[0m n_train, n_test [38;5;241m=[39m _validate_shuffle_split(
[1;32m   2449[0m     n_samples, test_size, train_size, default_test_size[38;5;241m=[39m[38;5;241m0.25[39m
[1;32m   2450[0m )
[1;32m   2452[0m [38;5;28;01mif[39;00m shuffle [38;5;129;01mis[39;00m [38;5;28;01mFalse[39;00m:

File [0;32m~/opt/miniconda3/envs/cpsc330/lib/python3.10/site-packages/sklearn/utils/validation.py:321[0m, in [0;36m_num_samples[0;34m(x)[0m
[1;32m    319[0m         x [38;5;241m=[39m np[38;5;241m.[39masarray(x)
[1;32m    320[0m     [38;5;28;01melse[39;00m:
[0;32m--> 321[0m         [38;5;28;01mraise[39;00m [38;5;167;01mTypeError[39;00m(message)
[1;32m    323[0m [38;5;28;01mif[39;00m [38;5;28mhasattr[39m(x, [38;5;124m"[39m[38;5;124mshape[39m[38;5;124m"[39m) [38;5;129;01mand[39;00m x[38;5;241m.[39mshape [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m    324[0m     [38;5;28;01mif[39;00m [38;5;28mlen[39m(x[38;5;241m.[39mshape) [38;5;241m==[39m [38;5;241m0[39m:

[0;31mTypeError[0m: Expected sequence or array-like, got <class 'NoneType'>
TypeError: Expected sequence or array-like, got <class 'NoneType'>

